language: python
python:
  - "3.8"
addons:
  ssh_known_hosts: 143.244.132.151
before_install:
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa
install:
  - pip install -r requirements.txt
script:
  - "true"
after_success:
  - bash ./deploy.sh
notifications:
  email:
    recipients:
      - tech.mesalumniassn@gmail.com
    on_failure: always
